programs:
  ls_demo:
    cmd: "/bin/ls"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: false
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 2
    starttime: 2
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/cat_demo.stdout
    stderr: /tmp/cat_demo.stderr
    env:
      STARTED_BY: taskmaster
      MODE: demo

  sleep_test:
    cmd: "/bin/sleep 10"
    numprocs: 1
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 3
    starttime: 3
    stopsignal: TERM
    stoptime: 5
    stdout: /tmp/sleep_test.stdout
    stderr: /tmp/sleep_test.stderr
    env:
      STARTED_BY: taskmaster
      TYPE: background