# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    config.yaml                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lnaidu <lnaidu@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/09/17 07:48:11 by lnaidu            #+#    #+#              #
#    Updated: 2025/11/05 06:30:09 by lnaidu           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

programs:
  hello:
    cmd: "/bin/echo hello-from-taskmaster"
    numprocs: 1
    autostart: true
    autorestart: unexpected
    exitcodes: 0
    stdout: /tmp/hello.stdout
    stderr: /tmp/hello.stderr

  sleeper:
    cmd: "/bin/sleep 10"
    numprocs: 2
    autostart: true
    autorestart: unexpected
    exitcodes: 0
    stdout: /tmp/sleeper.stdout
    stderr: /tmp/sleeper.stderr